[package]
name = "server"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
argh = "0.1.5"
async-bincode = "0.6.1"
axum = "0.1.3"
bincode = "1.3.3"
eyre = "0.6.5"
futures-util = { version = "0.3.16", default-features = false }
humantime = "2.1.0"
serde = "1.0.128"
serde_json = "1.0.66"
shared = { path = "../shared" }
tokio = { version = "1.10.0", features = ["io-util", "macros", "rt-multi-thread"] }
tower-http = { version = "0.1.1", features = ["trace"] }
tracing = "0.1.26"
tracing-error = "0.1.2"
tracing-subscriber = "0.2.20"
