[package]
name = "server"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
argh = "0.1.5"
async-trait = "0.1.51"
axum = "0.2.1"
color-eyre = "0.5.11"
eyre = "0.6.5"
futures-util = { version = "0.3.16", default-features = false }
humantime = "2.1.0"
serde = "1.0.129"
serde_cbor = "0.11.2"
serde_json = "1.0.66"
shared = { path = "../shared" }
sled = { version = "0.34.6", optional = true }
time = { version = "0.3.1", default-features = false }
tokio = { version = "1.10.1", features = ["io-util", "macros", "rt-multi-thread"] }
tokio-serde-cbor = "0.6.0"
tokio-util = { version = "0.6.1", features = ["codec"] }
tower-http = { version = "0.1.1", features = ["trace"] }
tracing = "0.1.26"
tracing-error = "0.1.2"
tracing-subscriber = "0.2.20"
