[package]
name = "server"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
argh = { version = "0.1.6", optional = true }
async-trait = "0.1.51"
axum = "0.2.3"
color-eyre = { version = "0.5.11", optional = true }
eyre = { version = "0.6.5", optional = true }
futures-util = { version = "0.3.17", default-features = false }
humantime = { version = "2.1.0", optional = true }
hyper = "0.14.12"
serde = "1.0.130"
serde_cbor = "0.11.2"
serde_json = "1.0.67"
shared = { path = "../shared" }
sled = { version = "0.34.6", optional = true }
thiserror = "1.0.29"
time = { version = "0.3.2", default-features = false }
tokio = { version = "1.11.0", features = ["io-util", "macros", "rt-multi-thread"] }
tokio-serde-cbor = "0.6.0"
tokio-util = { version = "0.6.8", features = ["codec"] }
tower-http = { version = "0.1.1", features = ["trace"] }
tracing = "0.1.26"
tracing-error = { version = "0.1.2", optional = true }
tracing-subscriber = { version = "0.2.20", optional = true }

[lib]
name = "server"

[features]
bin = ["argh", "color-eyre", "eyre", "humantime", "tracing-error", "tracing-subscriber"]

[[bin]]
name = "server"
required-features = ["bin"]
