[package]
name = "server"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
argh = "0.1.5"
axum = "0.1.3"
color-eyre = "0.5.11"
eyre = "0.6.5"
serde = "1.0.128"
serde_json = "1.0.66"
shared = { path = "../shared" }
tokio = { version = "1.10.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.1.1", features = ["trace"] }
tracing = "0.1.26"
tracing-error = "0.1.2"
tracing-subscriber = "0.2.20"
